azs:
- name: az1
  cloud_properties:
    datacenters:
    - clusters:
      - Core: {resource_pool: grafana}

networks:
- name: default
  type: manual
  subnets:
  - range: 192.168.10.0/24
    gateway: 192.168.10.253
    az: az1
    dns: [192.168.10.1, 8.8.8.8]
    static: [192.168.10.20-192.168.10.22]
    reserved:
    - 192.168.10.1-192.168.10.9
    cloud_properties:
      name: pg-mglab-mgmt-vlan-10-UT


vm_types:
- name: default
  cloud_properties:
    cpu: 1
    ram: 1024
    disk: 3240
- name: grafana-node
  cloud_properties:
    cpu: 2
    ram: 2048
    disk: 4096
  env:
    bosh:
      password: "$6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0"
      # c1oudc0w is a default password for vcap user


disk_pools:
- name: grafana-disk
  disk_size: 20_480


compilation:
  workers: 4
  reuse_compilation_vms: true
  az: az1
  vm_type: default
  network: default
